version: '2'
services:
  drupal:
    build:
      context: ../../drupal
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    ports:
      - "80:80"
    restart: 'unless-stopped'
    volumes:
      - /credentials/drupal/rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - /credentials/drupal/rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - /data/drupal-logs:/var/log/httpd
    volumes_from:
      - drupal_data
    environment:
      - FORTAWESOME_REGISTRY
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080

  # Drupal production data
  drupal_data:
    image: redhatdeveloper/drupal-data:latest
    volumes:
      - /var/www/drupal/web/config/active
      - /var/www/drupal/web/sites/default/files
      - /docker-entrypoint-initdb.d

  #
  # Environment actions
  #
  database_sync:
    user: root
    build:
      context: ../../backup
      args:
       http_proxy: proxy01.util.phx2.redhat.com:8080
       https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby developer.redhat.com/_docker/lib/staging-sync/run.rb"
    volumes:
      - ../../../:/home/jenkins_developer/developer.redhat.com
      - /credentials/db/my.cnf:/root/.my.cnf
      - /data/database-sync:/backup
    volumes_from:
      - drupal_data
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080

  export:
    build:
      context: ../../export
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/export/export.rb rhdp-drupal.stage.redhat.com"
    volumes:
      - /data/drupal-export:/export
      - /credentials/rsync:/home/jenkins_developer/.ssh
      - /credentials/akamai/edgerc:/home/jenkins_developer/.edgerc
      - ../../../:/home/jenkins_developer/developer.redhat.com
      - ../../../images:/home/jenkins_developer/developer.redhat.com/_docker/lib/export/static/images:ro
    environment:
     - drupal.export.fail_on_missing
     - drupal.export.final_base_url=https://developers.stage.redhat.com/
     - drupal.export.attempt_invalidate_cache


  rollback:
    build:
     context: ../../export
     args:
      http_proxy: proxy01.util.phx2.redhat.com:8080
      https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/rollback/rollback.rb rhd@filemgmt.jboss.org:/stg_htdocs/it-rhd-stg-main-drupal"
    volumes:
     - /data/drupal-export:/export
     - /credentials/rsync:/home/jenkins_developer/.ssh
     - ../../../:/home/jenkins_developer/developer.redhat.com

  #
  # Testing
  #
  unit_tests:
    build:
      context: ../../awestruct
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    entrypoint: "bundle exec rake test"
