version: '2'
services:
  awestruct:
    build:
     context: ../../awestruct
     args:
      http_proxy: proxy01.util.phx2.redhat.com:8080
      https_proxy: proxy01.util.phx2.redhat.com:8080
    command:
      - "rake git_setup clean gen[drupal_staging]"
    links:
      - drupal
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - DRUPAL_HOST_PORT
      - DRUPAL_HOST_IP
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL

  drupal:
    build:
     context: ../../drupal
     args:
      http_proxy: proxy01.util.phx2.redhat.com:8080
      https_proxy: proxy01.util.phx2.redhat.com:8080
    ports:
      - "80:80"
    volumes:
      - ../../../images:/var/www/html/images
      - ../../../stylesheets/fonts:/var/www/html/fonts
      - ../../drupal/themes/:/var/www/html/themes
      - ../../drupal/modules/custom/:/var/www/html/modules/custom
      - /credentials/drupal/rhd.settings.php:/var/www/html/sites/default/rhd.settings.php
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080
      - DB_NAME=drupal
      # TODO: Drop these once we have rhd.settings.php working correctly
      - DB_USER=drupal
      - DB_PASSWORD=drupal
 #
 # Environment actions
 #
 export:
  user: root
  build:
   context: ../../awestruct
   args:
    http_proxy: proxy01.util.phx2.redhat.com:8080
    https_proxy: proxy01.util.phx2.redhat.com:8080
  entrypoint: "ruby _docker/lib/export/export.rb developer-drupal.web.stage.ext.phx2.redhat.com"
  volumes:
   - /data/drupal-export:/export
   - /credentials/rsync:/home/awestruct/.ssh