version: '2'
services:
  drupal:
    build: ../../drupal
    ports:
      - "${DRUPAL_HOST_PORT}:80"
    links:
      - drupalmysql
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro
    volumes_from:
     - drupal_data

  drupalmysql:
    image: mariadb:10.0.24
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    expose:
      - "3306"
    volumes_from:
     - drupal_data

  # Drupal production data
  drupal_data:
   image: redhatdeveloper/drupal-data-lite:latest
   volumes:
    - /var/www/drupal/web/config/active
    - /var/www/drupal/web/sites/default/files
    - /docker-entrypoint-initdb.d

  #
  # Environment actions
  #
  export:
   build: ../../export
   volumes:
    - ../../../:/home/jenkins_developer/developer.redhat.com
    - ../../awestruct/overlay/ssh-key:/home/jenkins_developer/.ssh
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'ruby _docker/lib/export/export.rb rhdp-jenkins-slave.lab4.eng.bos.redhat.com:${DRUPAL_HOST_PORT}'"
   network_mode: "host"
   environment:
    - github_status_enabled=true
    - github_status_api_token
    - github_status_context=exported-site-preview
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${export_destination}
    - github_status_sha1=${ghprbActualCommit}
    - drupal.export.fail_on_missing
    - drupal.export.final_base_url=${export_destination}

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'bundle exec rake test'"
   environment:
    - github_status_enabled=true
    - github_status_api_token
    - github_status_context=build-unit-tests
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}
    - github_status_sha1=${ghprbActualCommit}
    - github_status_initialise=build-unit-tests,js-unit-tests,js-e2e-tests,js-mobile-e2e-tests,broken-link-checks,exported-site-preview,drupal-site
