base_url: https://developers.stage.redhat.com
verbose: true
remote: true
skips:
  - !ruby/regexp /^https?:\/\/localhost:(8|9)\d{3}.*/
  - !ruby/regexp /^https?:\/\/127.0.0.1:(8|9)\d{3}.*/
  - http://10.1.2.2:8000/
  - !ruby/regexp /-YOUR_DOMAIN_NAME\.rhcloud\.com/
  - !ruby/regexp /-YOUR_DOMAIN\.rhcloud\.com/
  - !ruby/regexp /(.+?)app-name(.+?)-(.+?)domain-name(.+?)\.rhcloud\.com/
  - !ruby/regexp /^http:\/\/logout@127.0.0.1:8080\/.*/
  - !ruby/regexp /^mailto:/
  - !ruby/regexp /^irc:/
  - !ruby/regexp /^https?:\/\/(www\.)?linkedin\.com\/shareArticle.*/
  - !ruby/regexp /^https?:\/\/(www\.)?linkedin\.com\/.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/sharer\.php.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/.*\?rel=author$/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/Unsolicted\+Responses+/
  - !ruby/regexp /^http:\/\/www-stg.jboss.org\/pr\/\d{3}\/build\/\d{4}\/projects\/issues.jboss.org\/browse\/WINDUP+/
  - !ruby/regexp /^https:\/\/devstudio.jboss.com\/central\/install\?connectors=org.jboss.tools.aerogear.hybrid+/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/Security\+Token\+Server\+%28STS%29+/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/SAML\+Authenticators\+\%28Tomcat\%2CJBossAS\%29+/
  - !ruby/regexp /^https:\/\/developers\.stage\.redhat\.com\/quickstarts\.*\/.*/

ignores:
  - code: 202
  - code: 203
  - code: 403
  - code: 502
  # This is not an error in real browsers.It is a known issue with PhantomJS https://github.com/ariya/phantomjs/issues/12750
  - url: !ruby/regexp /https:\/\/f\.vimeocdn\.com\/.*/
  - url: !ruby/regexp /ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https:\/\/player\.vimeo\.com\/.*/
  - url: !ruby/regexp /https:\/\/ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https?:\/\/(www\.)?linkedin\.com\/.*/
  - url: !ruby/regexp /https?:\/\/(www\.)?linkedin\.com\/.*/

environments:
  - http://rhdp-drupal.stage.redhat.com
  - https://rhdp-drupal.stage.redhat.com

ax_page_retys: 6
max_retrys: 6
threads: 10
report: blinkr.html
