version: '2'
services:
  rhd_blinkr_testing:
    build: ../
    volumes:
    - ../../../../:/home/blinkr/developers.redhat.com
    working_dir: /home/blinkr/developers.redhat.com/_tests/blc/blinkr
    environment:
    - CONFIG
    - GRID_HOST=blinkr_chrome
    - GRID_PORT=4444

  blinkr_chrome:
    image: selenium/standalone-chrome-debug:3.14.0-arsenic
    volumes:
    - /dev/shm:/dev/shm
    ports:
    - "5900"
    links:
    - rhd_blinkr_testing
