version: '2'
services:
  awestruct:
    build: ../../awestruct
    command:
      - "rake git_setup clean gen[drupal_dev]"
    links:
      - drupal
      - searchisko
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - DRUPAL_HOST_PORT
      - DRUPAL_HOST_IP
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL

  drupal:
    build: ../../drupal
    ports:
      - "32769:80"
    links:
      - drupalmysql
      - searchisko
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ../../drupal/drupal-filesystem/web/themes/custom:/var/www/drupal/web/themes/custom
      - ../../drupal/drupal-filesystem/web/modules/custom:/var/www/drupal/web/modules/custom
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro

  drupalmysql:
    image: mariadb:10.0.15
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  mysql:
    build: ../../mysql
    volumes:
      - ../../mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=searchisko
      - MYSQL_USER=searchisko
      - MYSQL_PASSWORD=searchisko
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  searchisko:
    build: ../../searchisko
    expose:
     - "8080"
    ports:
     - "32772:8080"
    environment:
      - DB_NAME=searchisko
      - DB_USER=searchisko
      - DB_PASSWORD=searchisko
    links:
     - mysql
  #
  # Environment actions
  #
  export:
    extra_hosts:
     - "docker:${DOCKER_HOST_IP}"
    build: ../../awestruct
    volumes:
     - ../../../:/home/awestruct/developer.redhat.com
     - export:/export
    entrypoint: "ruby _docker/lib/export/export.rb docker:32769"

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "bundle exec rake test"

  acceptance_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - PARALLEL_TEST
      - CUCUMBER_TAGS
      - SELENIUM_HOST=http://selhub:4444/wd/hub
      - RHD_JS_DRIVER
      - RHD_DOCKER_DRIVER
      - BUILD_URL

#
# Volumes
#
volumes:
 export:
  driver: local

