version: '2'
services:
  awestruct:
    build: ../../awestruct
    command:
      - "rake git_setup clean gen[drupal_dev]"
    links:
      - drupal
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - DRUPAL_HOST_PORT
      - DRUPAL_HOST_IP
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL

  drupal:
    build: ../../drupal
    ports:
      - "80:80"
    links:
      - drupalmysql
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ../../drupal/drupal-filesystem/web/themes/custom:/var/www/drupal/web/themes/custom
      - ../../drupal/drupal-filesystem/web/modules/custom:/var/www/drupal/web/modules/custom
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro
    volumes_from:
      - drupal_data

  drupalmysql:
    image: mariadb:10.0.24
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"
    ports:
      - "3306"
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    volumes_from:
      - drupal_data

  apache:
   image: httpd:2.4.20
   command: "sh -c 'rm -f /usr/local/apache2/htdocs/index.html && httpd-foreground'"
   links:
    - drupal:docker
   expose:
    - 80
    - 9000
   ports:
    - "9000:9000"
   volumes:
    - export:/usr/local/apache2/htdocs
    - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

  # Drupal production data
  drupal_data:
   image: redhatdeveloper/drupal-data-lite:latest
   volumes:
    - /var/www/drupal/web/config/active
    - /var/www/drupal/web/sites/default/files
    - /docker-entrypoint-initdb.d

  #
  # Environment actions
  #
  export:
    links:
     - drupal:docker
    build: ../../export
    volumes:
     - ../../../:/home/jenkins_developer/developer.redhat.com
     - export:/export
    entrypoint: "ruby _docker/lib/export/export.rb docker"
    environment:
     - drupal.export.fail_on_missing
     - drupal.export.final_base_url=http://docker:9000/

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "bundle exec rake test"

#
# Volumes
#
volumes:
 export:
  driver: local
