environment: dev
broker: https://broker.staging.redhat.com/partner/drc/userMapping?redirect=
downloadManager:
  baseUrl: 'https://developers.stage.redhat.com'
  fileBaseUrl: '//developers.stage.redhat.com/download-manager/file/'
keycloak:
  accountUrl: 'https://developers.stage.redhat.com/auth/realms/rhd/account/'
  authUrl: 'https://developers.stage.redhat.com/auth/'
drupal:
  host: docker
  port: "80"
  admin:
    name: 'admin'
    password: 'admin'
    mail: 'admin@example.com'
searchisko:
  protocol: 'http'
  host: dcp.stage.jboss.org
  port: "80"
  baseProtocolRelativeUrl: 'dcp.stage.jboss.org:80'
database:
  host:  drupalmysql
  port: '3306'
  username: 'drupal'
  password: 'drupal'
  name: 'drupal'
dtm_code: https://www.redhat.com/dtm-staging.js
sentry_track: true
sentry_script: 'https://cdn.ravenjs.com/3.24.0/raven.min.js'
sentry_code: 'https://cc00364690f241ffb2fcb39254d7f23f@sentry.io/115436'
