environment: dev
broker: https://broker.staging.redhat.com/partner/drc/userMapping?redirect=
downloadManager:
  baseUrl: 'https://developers.stage.redhat.com'
  fileBaseUrl: '//developers.stage.redhat.com/download-manager/file/'
keycloak:
  accountUrl: 'https://developers.stage.redhat.com/auth/realms/rhd/account/'
  authUrl: 'https://developers.stage.redhat.com/auth/'
drupal:
  host: docker
  port: "80"
searchisko:
  protocol: 'http'
  host: dcp.stage.jboss.org
  port: "80"
  baseProtocolRelativeUrl: 'dcp.stage.jboss.org:80'
database:
  host:  drupalmysql
  port: '3306'
  username: 'drupal'
  password: 'drupal'
  name: 'drupal'

