environment: dev
broker: https://broker.staging.redhat.com/partner/drc/userMapping?redirect=
downloadManager:
  baseUrl: 'https://developers.stage.redhat.com'
  fileBaseUrl: '//developers.stage.redhat.com/download-manager/file/'
keycloak:
  accountUrl: 'https://developers.stage.redhat.com/auth/realms/rhd/account/'
  authUrl: 'https://developers.stage.redhat.com/auth/'
  scriptUrl: 'https://developers.redhat.com/auth/js/keycloak.js'
  content_editor_sso:
    redirect_url: 'http://localhost'
    client_id: 'rhd-web-cms-localdev'
    client_secret: 'not-a-secret'
    keycloak_base: 'https://developers.stage.redhat.com/auth'
    keycloak_realm: 'rhd'
    authorization_endpoint_kc: 'https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/auth'
    token_endpoint_kc: 'https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/token'
    userinfo_endpoint_kc: 'https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/userinfo'
drupal:
  host: docker
  port: "80"
  admin:
    name: 'admin'
    password: 'admin'
    mail: 'admin@example.com'
searchisko:
  protocol: 'https'
  host: dcp.stage.jboss.org
  port: "443"
  baseProtocolRelativeUrl: 'dcp.stage.jboss.org:443'
database:
  host:  drupalmysql
  port: '3306'
  username: 'drupal'
  password: 'drupal'
  name: 'rhd_mysql'
sentry_track: false
sentry_script: 'https://cdn.ravenjs.com/3.24.0/raven.min.js'
sentry_code: 'https://cc00364690f241ffb2fcb39254d7f23f@sentry.io/115436'
