version: '2'
services:
  rhd_unit_testing:
    build: ../../../_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend
    user: '1000'
    volumes:
    - ../../../:/developers.redhat.com
    - ../../../_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/report:/testing/src/tests/unit/report
    entrypoint:
      - '/bin/bash'
      - '-c'
      - 'source /etc/scl_enable && ruby /developers.redhat.com/_docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb npm test && cp src/tests/unit/report/index.html src/tests/unit/report/unit-test-report.html'
    working_dir: /testing
    environment:
    - github_status_enabled
    - github_status_api_token
    - github_status_context
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}artifact/_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/report/unit-test-report.html
    - github_status_sha1