verbose: true

skips:
  - !ruby/regexp /^https:\/\/developers\.redhat\.com\/quickstarts\.*\/.*/

ignores:
  - code: 202
  - code: 203
  - code: 403
  - code: 502
  # This is not an error in real browsers.It is a known issue with PhantomJS https://github.com/ariya/phantomjs/issues/12750
  - url: !ruby/regexp /https:\/\/f\.vimeocdn\.com\/.*/
  - url: !ruby/regexp /ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https:\/\/player\.vimeo\.com\/.*/
  - url: !ruby/regexp /https:\/\/ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https?:\/\/(www\.)?linkedin\.com\/.*/
  - url: !ruby/regexp /https?:\/\/(www\.)?linkedin\.com\/.*/

environments:
  - http://developer-drupal.web.prod.ext.phx2.redhat.com
  - https://developer-drupal.web.prod.ext.phx2.redhat.com

ignore_external: true

ignore_ssl: true
max_page_retys: 5
max_retrys: 5
browser: phantomjs
ignore_fragments: true
phantomjs_threads: 8
report: blinkr.html
