verbose: true
base_url: https://developers.redhat.com
hard_fail: false
skips:
  - !ruby/regexp /^https?:\/\/localhost:(8|9)\d{3}.*/
  - !ruby/regexp /^https?:\/\/127.0.0.1:(8|9)\d{3}.*/
  - http://10.1.2.2:8000/
  - !ruby/regexp /-YOUR_DOMAIN_NAME\.rhcloud\.com/
  - !ruby/regexp /-YOUR_DOMAIN\.rhcloud\.com/
  - !ruby/regexp /(.+?)app-name(.+?)-(.+?)domain-name(.+?)\.rhcloud\.com/
  - !ruby/regexp /^http:\/\/logout@127.0.0.1:8080\/.*/
  - !ruby/regexp /^mailto:/
  - !ruby/regexp /^irc:/
  - !ruby/regexp /^https?:\/\/(www\.)?linkedin\.com\/shareArticle.*/
  - !ruby/regexp /^https?:\/\/(www\.)?linkedin\.com\/.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/sharer\.php.*/
  - !ruby/regexp /^https?:\/\/(www\.)?facebook\.com\/.*\?rel=author$/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/Unsolicted\+Responses+/
  - !ruby/regexp /^http:\/\/www-stg.jboss.org\/pr\/\d{3}\/build\/\d{4}\/projects\/issues.jboss.org\/browse\/WINDUP+/
  - !ruby/regexp /^https:\/\/devstudio.jboss.com\/central\/install\?connectors=org.jboss.tools.aerogear.hybrid+/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/Security\+Token\+Server\+%28STS%29+/
  - !ruby/regexp /^https:\/\/docs.jboss.org\/author\/display\/PLINK\/SAML\+Authenticators\+\%28Tomcat\%2CJBossAS\%29+/
  # Heinze has agreed for us to ignore the following:
  - !ruby/regexp /^https:\/\/developers\.redhat\.com\/variants\/.*/
  - !ruby/regexp /^https:\/\/developer\.jboss\.org\/people\/Darrin\/.*/
  - !ruby/regexp /^https:\/\/github\.com\/jboss\-developer\/jboss\-jdg\-quickstarts\/tree\/.*/
  - !ruby/regexp /^https:\/\/github\.com\/jboss\-fuse\/quickstarts\/tree\/c6243b5\/.*/
  - !ruby/regexp /^http:\/\/www\.\jboss\.org\/jdf\/qcleuickstarts\/jboss\-as\-\quickstart\/guide\/.*/
  - !ruby/regexp /^..\/camel\-.*/
  - !ruby/regexp /^https:\/\/access\.redhat\.com\/site\/documentation\/JBoss_Fuse$/
  - https://access.redhat.com/site/documentation/JBoss_Fuse/index.html
  - !ruby/regexp /^..\/jboss\-javaee\-6_0\-with\-hibernate\-eap62\/index\/index\-2\.html$/
  - !ruby/regexp /^..\/jboss\-javaee\-6_0\-with\-deltaspike\-wfk\-24\/index\/index\-2\.html$/
  - !ruby/regexp /^http:\/\/dl\.dropbox\.com\/u\/65660684\/640px\-Roy_Thomson_Hall_Toronto.jpg$/
  - !ruby/regexp /^http:\/\/vimeo\.com\/ericschabell\/bpmsuite\-fuse\-integraiton\-demo\-run$/
  - !ruby/regexp /^https:\/\/github\.com\/jboss\-dockerfiles\/hawkular\/blob\/master\/hawkular\-aio\/README.md$/
  - http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart/guide/Introduction
  - http://vimeo.com/ericschabell/bpms-hr-employee-rewards-demo-run
  - https://pubs.vmware.com/workstation-12/index.jsp#com.vmware.ws.using.doc/GUID-0CE1AE01-7E79-41BB-9EA8-4F839BE40E1A.html
  - !ruby/regexp /^https:\/\/pubs\.vmware\.com\/workstation\-\d*\/.*/
  - !ruby/regexp /^https:\/\/developers\.redhat\.com\/quickstarts\.*\/.*/
  
ignores:
  - code: 202
  - code: 203
  - code: 502
  - code: 999
  # This is not an error in real browsers.It is a known issue with PhantomJS https://github.com/ariya/phantomjs/issues/12750
  - url: !ruby/regexp /https:\/\/f\.vimeocdn\.com\/.*/
  - url: !ruby/regexp /ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https:\/\/player\.vimeo\.com\/.*/
  - url: !ruby/regexp /https:\/\/ssl\.google-analytics\.com\/.*/
  - url: !ruby/regexp /https?:\/\/(www\.)?linkedin\.com\/.*/

max_page_retys: 5
max_retrys: 5
browser: phantomjs
ignore_fragments: true
phantomjs_threads: 8
report: blinkr.html
