version: '2'
services:
  rhd_blc_testing:
   build: ../
   volumes:
    - ../../../:/home/blc/developers.redhat.com
   entrypoint: ruby /home/blc/developers.redhat.com/_docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb
   working_dir: /home/blc/developers.redhat.com/_tests/blc
   environment:
    - github_status_enabled
    - github_status_api_token
    - github_status_context
    - github_status_repo=redhat-developer/developers.redhat.com
    - github_status_target_url=${BUILD_URL}artifact/blc/blinkr.html
    - github_status_sha1
