version: '2'
services:
  drupal:
    build: ../../drupal
    ports:
      - "80:80"
    links:
      - drupalmysql
      - searchisko
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ../../drupal/drupal-filesystem/web/themes/custom:/var/www/drupal/web/themes/custom
      - ../../drupal/drupal-filesystem/web/modules/custom:/var/www/drupal/web/modules/custom
      - ../../../images:/var/www/drupal/web/images:ro
      - ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro
    environment
      - FORTAWESOME_REGISTRY

  drupalmysql:
    image: mariadb:10.0.24
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"
    volumes:
      - ../../drupal/prod_db.sql.gz:/docker-entrypoint-initdb.d/prod_db.sql.gz

  mysql:
    build: ../../mysql
    volumes:
      - ../../mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=searchisko
      - MYSQL_USER=searchisko
      - MYSQL_PASSWORD=searchisko
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  searchisko:
    build: ../../searchisko
    expose:
     - "8080"
    ports:
     - "8080:8080"
    environment:
      - DB_NAME=searchisko
      - DB_USER=searchisko
      - DB_PASSWORD=searchisko
    links:
     - mysql

  apache:
   image: httpd:2.4.20
   command: "sh -c 'rm -f /usr/local/apache2/htdocs/index.html && httpd-foreground'"
   links:
    - drupal:docker
   expose:
    - 80
    - 9000
   ports:
    - "9000:9000"
   volumes:
    - export:/usr/local/apache2/htdocs
    - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

  #
  # Environment actions
  #
  export:
    links:
     - drupal:docker
    build: ../../export
    volumes:
     - ../../../:/home/jenkins_developer/developer.redhat.com
     - export:/export
    entrypoint: "ruby _docker/lib/export/export.rb docker"

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "bundle exec rake test"

#
# Volumes
#
volumes:
 export:
  driver: local
