rhdp_environment: local
rhdp_git_repo: https://github.com/redhat-developer/developers.redhat.com.git
rhdp_git_branch: master
drupal_db_host: mysql
drupal_db_user: root
drupal_db_password: password
drupal_url: developers.dev.redhat.com
drupal_previous_url: previous.developers.dev.redhat.com
drupal_next_url: next.developers.dev.redhat.com
drupal_content_editor_sso_client_id: test_client_id
drupal_content_editor_sso_client_secret: test_client_secret
drupal_backup_push: false
drupal_s3_bootstrap: false
drupal_s3_bucket: developersrhcdrupalbackup
drupal_s3_access_key: TBC
drupal_s3_secret_key: TBC
drupal_sentry_code: notAValidCode
drupal_google_api_key: notAValidApiKey
drupal_backup_clean: false
backup_name: testing