name: DevOps
sub_title: Innovate at the speed of open source with DevOps
long_description: Get the tools, the automation and the context you'll need to embrace DevOps
icon: icon-rh-icon-cloud-admin
tags:
  - DevOps
  - CI
  - CD
  - Continuous Delivery
  - Continuous Integration
left_section_icon: icon-rh-icon-talk-bubble-conversation
middle_section_icon: icon-rh-icon-circle-sphere
right_section_icon: icon-rh-icon-tools

