drupal:
  build: ./drupal
  ports:
    - "8081:80"
  links:
    - drupalmysql
  volumes:
    - ../_drupal/themes:/var/www/html/sites/all/themes
    - ../_drupal/scripts:/opt/drupal/bin
  environment:
    - DB_NAME=drupal
    - DB_USER=drupal
    - DB_PASSWORD=drupal
drupalmysql:
  build: ./mysql
  environment:
    - DB_NAME=drupal
    - DB_USER=drupal
    - DB_PASSWORD=drupal
  ports:
    - "13306:3306"
mysql:
  build: ./mysql
  environment:
    - DB_NAME=searchisko
    - DB_USER=searchisko
    - DB_PASSWORD=searchisko
  ports:
    - "3306:3306"
elasticsearch:
  build: ./elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
searchisko:
  build: ./searchisko
  ports:
   - "8080:8080"
  environment:
    - DB_NAME=searchisko
    - DB_USER=searchisko
    - DB_PASSWORD=searchisko
  links:
   - mysql
   - elasticsearch
searchiskoconfigure:
  build: ./searchisko_configure
  links:
   - mysql
   - elasticsearch
   - searchisko
